spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**,/api/v1/auth/**
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/api/v1/clients/**
        - id: comms-service
          uri: lb://comms-service
          predicates:
            - Path=/api/v1/communications/**

  kubernetes:
    discovery:
      all-namespaces: true